# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_cogcache_wrappers", use_symbols = TRUE, package_name = "cogcache")

#' @usage NULL
#' @useDynLib cogcache, .registration = TRUE
NULL

#' Decode a DEFLATE-compressed tile with predictor=2 undo.
#'
#' Takes raw compressed bytes (as R raw vector), tile dimensions, and
#' predictor type. Returns decoded pixel values as integer vector.
#'
#' @param raw_bytes Raw vector of compressed tile bytes
#' @param tile_width Integer tile width in pixels
#' @param tile_height Integer tile height in pixels
#' @param predictor Integer predictor type (1 = none, 2 = horizontal diff)
#' @return Integer vector of decoded UInt16 pixel values
#' @export
rust_decode_tile <- function(raw_bytes, tile_width, tile_height, predictor) .Call(wrap__rust_decode_tile, raw_bytes, tile_width, tile_height, predictor)

#' Fetch a tile via HTTP range request and decode it.
#'
#' Performs the full pipeline in Rust: HTTP range fetch, DEFLATE decompress,
#' predictor undo. Returns decoded pixel values as integer vector.
#'
#' @param url Character string URL (without /vsicurl/ prefix)
#' @param byte_offset Numeric byte offset in the file
#' @param byte_length Integer number of bytes to fetch
#' @param tile_width Integer tile width in pixels
#' @param tile_height Integer tile height in pixels
#' @param predictor Integer predictor type (1 = none, 2 = horizontal diff)
#' @return Integer vector of decoded UInt16 pixel values
#' @export
rust_fetch_decode_tile <- function(url, byte_offset, byte_length, tile_width, tile_height, predictor) .Call(wrap__rust_fetch_decode_tile, url, byte_offset, byte_length, tile_width, tile_height, predictor)


# nolint end
